# Generated by Django 4.0.1 on 2022-08-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان پروژه')),
                ('img', models.ImageField(blank=True, upload_to='img', verbose_name='عکس پروژه')),
                ('description', models.TextField(verbose_name='شرح پروژه')),
            ],
        ),
    ]
