# Generated by Django 4.0.1 on 2022-08-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects_model',
            name='img',
            field=models.ImageField(blank=True, upload_to='staticroot/img', verbose_name='عکس پروژه'),
        ),
    ]
